sudo: false
language: clojure
jdk:
- oraclejdk8
lein: 2.7.1
services:
- couchdb
cache:
  directories:
  - "$HOME/.m2"
script:
- lein2 test!
- lein2 eastwood
- lein2 kibit
branches:
  only:
  - master
  - dev
notifications:
  slack:
    secure: KP14WdC7/2BXM5lEsFgCPUhRchXn4zMk1AmAS1QQEqhHT6rDb2r3jbKBJV6R3TTpaMx2lve1Wwtbkhzpbr2uczYnuXOxqqbkrGxNXFEWm0F4/w/mjtUBcRmAVIwzTc5akrfrZ0v+pwD2HkSJRoNaP4HiKCXzgq2mf0JasGcf7kc=
