sudo: false
language: clojure
lein: lein2
cache:
  directories:
    - $HOME/.m2
script:
  - lein2 test!
  - lein2 eastwood
branches:
  only:
    - master
    - dev
jdk:
  - oraclejdk8
services:
  - couchdb
notifications:
  hipchat:
    rooms:
      - ec1ead2b384476ea5bcb232b5bb9b6@Snooty Monkey